#!/bin/bash

# Attach to a Mininet host and run a command

if [ -z $1 ]; then
  echo "usage: $0 host cmd [args...]"
  exit 1
else
  host=$1
fi

container=`docker ps | grep "mn.$host$" | awk '{print $10};'`
pid=`ps ax | grep "mininet:$host$" | grep bash | grep -v mnexec | awk '{print $1};'`

if [ "$container" == "" ]; then
  if echo $pid | grep -q ' '; then
    echo "Error: found multiple mininet:$host processes"
    exit 2
  fi
fi

if [ "$container" == "" ] && [ "$pid" == "" ]; then
  echo "Could not find Mininet host $host"
  exit 3
fi

if [ -z $2 ]; then
  cmd='bash'
else
  shift
  cmd=$*
fi

cgroup=/sys/fs/cgroup/cpu/$host
if [ -d "$cgroup" ]; then
  cg="-g $host"
fi

# Check whether host should be running in a chroot dir
rootdir="/var/run/mn/$host/root"
if [ -d $rootdir -a -x $rootdir/bin/bash ]; then
    cmd="'cd `pwd`; exec $cmd'"
    cmd="chroot $rootdir /bin/bash -c $cmd"
fi

if [ "$container" != "" ]; then
  cmd="docker exec $container bash -c '$cmd'"
else
  cmd="exec sudo mnexec $cg -a $pid $cmd"
fi
eval $cmd
