# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
	config.vm.provider "virtualbox" do |v|
  		v.memory = 2048
  		v.cpus = 2
	end
	config.vm.network "public_network"
  config.vm.provision "shell", path: "setup.sh"
end
