- hosts: localhost
  tasks:
   - name: epel release
     yum:
       name: epel-release
       state: latest

   - name: openstack repo (for OVS)
     yum:
       name: centos-release-openstack-pike
       state: latest
   
   - name: updates apt
     yum:
       name: '*'
       state: latest

   - name: install basic packages
     yum: name={{item}} state=latest
     with_items:
       - gcc
       - yum-utils
       - device-mapper-persistent-data
       - lvm2
       - ca-certificates
       - curl
       - python-setuptools
       - python-devel
       - python-pip
       - iptables

   - name: install Docker CE
     shell: curl -S https://get.docker.com | sh

   - name: start Docker
     shell: systemctl start docker

   - name: start Docker on startup
     shell: systemctl enable docker

   - name: install pytest
     pip: name=pytest state=latest

   - name: install docker-py
     pip: name=docker version=2.0.2

   - name: install python-iptables
     pip: name=python-iptables state=latest

   - name: built and install Containernet (using Mininet installer)
     shell: containernet/util/install.sh
     args:
       chdir: ../../

   - name: install Containernet Python egg etc.
     shell: make develop
     args:
       chdir: ../

   - name: download 'ubuntu' docker image for Containernet example
     shell: docker pull ubuntu:trusty
     tags:
        - notindocker
