- hosts: localhost
  tasks:
   - name: epel release
     yum:
       name: epel-release
       state: latest

   - name: openstack repo (for OVS)
     yum:
       name: centos-release-openstack-pike
       state: latest
   
   - name: updates yum
     yum:
       name: '*'
       state: latest

   - name: install basic packages
     yum: name={{item}} state=latest
     with_items:
       - net-tools
       - python-setuptools
       - python-devel
       - python-pip
       - curl
       - iptables
       - initscripts
       - yum-utils
       - device-mapper-persistent-data
       - lvm2
       - ca-certificates
       - curl
       - python-setuptools
       - python-devel
       - python-pip
       - iptables
       - gcc
       - sudo

   - name: install Docker CE (1/3)
     shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

   - name: install Docker CE (2/3)
     yum:
       name: docker-ce
       state: latest

   - name: install Docker CE (3/3)
     systemd: name=docker state=started
     tags:
        - notindocker

   - name: install pytest
     pip: name=pytest state=latest

   - name: install docker-py
     pip: name=docker version=2.0.2

   - name: install python-iptables
     pip: name=python-iptables state=latest

   - name: build and install Containernet (using Mininet installer)
     shell: containernet/util/install.sh
     args:
       chdir: ../../

   - name: install Containernet Python egg etc.
     shell: make develop
     args:
       chdir: ../

   - name: download 'ubuntu' docker image for Containernet example
     shell: docker pull ubuntu:trusty
     tags:
        - notindocker
